[tool.poetry]
name = "disparate-vulnerability"
version = "0.1.0"
description = "Code accompanying the 'Disparate Vulnerability to Membership Inference Attacks' paper"
authors = ["Bogdan Kulynych"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
numpy = "^1.21.2"
scipy = "^1.7.1"
pandas = "^1.3.3"
matplotlib = "^3.4.3"
seaborn = "^0.11.2"
tqdm = "^4.62.2"
joblib = "^1.0.1"
sklearn = "^0.0"
fairlearn = "^0.7.0"
diffprivlib = "^0.4.1"
statsmodels = "^0.12.2"
jupyter = "^1.0.0"
jupytext = "^1.12.0"


[tool.poetry.dev-dependencies]
pre-commit = "^2.15.0"
[build-system]
requires = ["poetry-core==1.1.8"]
build-backend = "poetry.core.masonry.api"
